[package]
name = "haul"
version ="0.3.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.59", features = ["derive"]}
rusqlite = { version="0.38.0", features=["bundled"]}
chrono = "0.4.43"
colored = "3.1.1"
directories = "6.0.0"
